title: MoCapAct
description: A Multi-Task Dataset for Simulated Humanoid Control
authors: Nolan Wagener, Andrey Kolobov, Felipe Vieira Frujeri, Ricky Loynd, Ching-An Cheng, Matthew Hausknecht
buttons:
  Code: 'https://github.com/nolanwagener/MoCapAct'
  #Blog: TODO
  #Paper (arXiv): TODO
  #Paper (OpenReview): TODO
  #Dataset: TODO
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

